# Generated by Django 3.1.1 on 2021-10-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPessoa', models.CharField(help_text='max. 200 caracteres', max_length=200, verbose_name='idPessoa')),
                ('categoria', models.CharField(choices=[('socio', 'Socio'), ('aluno', 'Aluno'), ('socio e aluno', 'Socio e Aluno')], max_length=255)),
                ('plano', models.CharField(choices=[('individual', 'Individual'), ('familiar', 'Familiar')], max_length=255)),
                ('status', models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='max. 200 caracteres', max_length=200, verbose_name='Nome')),
                ('rg', models.IntegerField()),
                ('cpf', models.IntegerField()),
                ('telefone', models.BigIntegerField()),
                ('telefonecelular', models.BigIntegerField()),
                ('datanascimento', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.CharField(max_length=200, verbose_name='idCliente')),
                ('local', models.CharField(choices=[('quadra de tênis', 'Quadra de Tênis'), ('natação', 'Natação'), ('quadra de tênis (saibro)', 'Quadra de Tênis (Saibro)'), ('academia', 'Academia')], max_length=255)),
                ('datareserva', models.DateField()),
                ('horareserva', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
