# Generated by Django 3.1.1 on 2021-11-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0007_auto_20211029_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='horareserva_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora da reserva (Fim)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='datareserva',
            field=models.DateField(blank=True, null=True, verbose_name='Data da reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='horareserva',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora da reserva (Inicio)'),
        ),
    ]
