# Generated by Django 3.1.1 on 2021-11-18 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0009_auto_20211118_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainMenu.pessoa', verbose_name='Cliente'),
        ),
    ]
